[theme]
primaryColor = "#2a4ebb"         
base = "light"    
secondaryBackgroundColor = "#F0F2F6"  
textColor = "#272931"         
[server]
headless = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"

[app]
title = "Audio to Text Transcription App ğŸ™ï¸"
favicon = "https://cdn-icons-png.flaticon.com/512/2927/2927122.png"  
